---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-auth
  namespace: postgresql
spec:
  encryptedData:
    password: AgCef+wDxpjQiUVPYqnW7TMMScbjgXhzh5s7zbarkhdjIjf5d2fGQMjAwoSCs01me54UgAVMUj1UqCSHkLCn2RQnCLSZhHaArrAF5fXMn4cgVBYrHPvDUs1mRDf8aRW+FAISxaF9QraVTooH8U5FljlY8VSZsifdedY8szG62DPl9nqPvBRMfTLpTiy9BS9oc6rcrLOziwyV8iBM6hg1orFrLqMJvEb6WgcGQbRFr/aUkQPbsF1UL6O7C8cxRQZRXm+nNAuPlrHje08UXcghlcd/8O0NaciZrKOv+HqYACbRp0OS4YofdvlPiN9JSRP4FuiozcdAfGMNcKFWwC3HUmmbcJQqQ/Hz6Vzi2DIs+j4RslAIxjwZOpbvlUr8pgQQShBdYnln6yTaGtR8FBeWn4844MpYMGEKRdZI9/ZEsXZ1peN7fDvr8NkWpfjqFhrkkze/iGMlqyU18RS8Zc9VWuIWUw9rqEBdnZMUNIXXnf9JPCcKfnKP861gH/1FapAjfBmkbxzjPyVwaKaY0iy50/m+T0nVACm+Jt5PixV2Wt2EX8kwHwuJmMPq6/y9j05uG1xNbD25S0WE6xrLftx2B4i3niyPoMBsrMDrmeDRArZmMuDBxah+7fyPHRBmXlfzwXP+LEuOmLjQCgXW7lF1EUgwMPOKzv1m+rLTD3/LTgiFcg9rmtXL3GmQWPSBeLCTFCoFF2Q6WrrBNh6VV7Ev74WG6jTLDIvrIa2fvxYiXM/DXg==
    postgres-password: AgCF6VXo0EIvD41d/nSpN3P8h7eeEBac6rn4dExEqPjc23x3lzEn9/WOG+GDyTfSU/LF+JQCLqzv9mOcKN6bvhPQGXjSTqqJGcIBnfWFf3c32kG/K7q0aJbmQhtnrBkYaimy4MnrvKSDZz+uX8PMiuRiCTwL18XfDx+3rw4Obv4PuYLcqPDRz/jAoUni9fXSHM2KCICS88Xv/9hY9eBwHWYByIVWL2P+n/iZmB99CcqzAQX3U4AZ5kecLaVHwH9upq7CId9U1YTDEQjTSyNI1vwlfi8211wypGv+Ci57NZT4No4VGgg+LK4AJ2IUWa7gt9Hyhs7wIFUXyt5Gdj8f6ZF51E964j3gGGk0dXJMmuEAPO7Cimxjv7rWagApnhwMo80QqTBBij/81DXailonG/wK08MjKN+rr0tjLSL7/PG98FNisPClTzk9nduO8W/1SxDFkuH+/JhCYxfRVH/VK7inuCk71It7dgnHSVtKHQ8rfFmrT6/oghGKFFwYmDrKrKazMlkgqteKXrNelh7u1izulultsBueC5gyv3HOY/ZXJnsQgbtx0tuA3+VNxgsaJYTU1CEibj2sAvnEINb5M5xinxDH7oSfI27turuTlmvToJimQJgX69j+8cL15aoT7MWGd7oBamU108RYLXnc5xbQYSZKvZstAOdQNLFt4bwNo96m9HXtwW7ueM0SyH7FhgUQ1I9la9078HihJvq/TNaVCNUlMgOGxOy7QtHcuay/Zw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-auth
      namespace: postgresql
