---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgAArR9wPHIcWw9YWCWNFEa5gKxNBqnawioWKztQjEsOGyhpmmywhZ6rzKGlw+3ozrw4bhi+7vOaEA+feujcBeFQzof9HWZ+dtwCaB9ztvo2yAgKkMEjkRIplNuPYoht9Mh58OVw87nxAfZ0xb0pAQxoE3QkUl2DMXzEgkRurorVQEgiwwHAnf56wkITxHSOWAQPOl24dbX7QHM0CkxkOzLCIHnmTuXWeiVlIQNIsd/uTaFBEQYoRJbv3sywzwWKZpasVvIl9Mw5BKw/sUQe8pW6SxIcP8WFLRVv8Zxf3Vt806gmrE4/SHVZpvwHLx5A2kpaR0QPMwD7ANYyHGkY7IOae98Db6Y1DnpluWDaGiTeMqWly6pjqOfd3YRB+qAhlU8WPHNhgVv3xPpyr55oeUsUcMgkaxVYwu8Sw+6U4pvMwXpDsUm1JuIV1eZWjBl/5rL4yr2S1YVceTKWRIK8q2h6sfOrPB6Szl6SMeZGRQbFgiOHMZRN3JKnIxO4FCc6JD8OF6yFZ7f/2kTNOd5xgzWAcp60ooFwUnF+tZGlx4vv7Qom21oM+OW6Nj0zD6W4cghzxQCayhLmLDV90r8TJyl7P5Yg0bo51rbRBt06ddZC9nm1ywvw1nwHPB4x4mYVtUl4UdVYZ5kAbjIFSSmHOvr56Fb6I/ss6pVSYtmqPGpsbowiGc5sscmB6oXqk3vrRg4IZ5p5C9l1/cUia+4qaREHE1iMKDV4JQdRrNVz+tXEiA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
