---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-auth
  namespace: postgresql
spec:
  encryptedData:
    password: AgBjSo0fngYB01TC439HOEGxd7zPGckJ5USCtcVbzDlr2IEpTPU2EciG+K+SxvpHGPrCcQ3JxjihY76hPJZ78g89gAwXnSMI1mawF1PXCNhyd9LI+fqcm6fHMT71S2SEBSrhBjwfVXoZ4pQISVzLiGJNj7IAZYOHpNbv2vL74RQCGa6age/9J0h+t30VgJP9+QtJxwv5RjrqRFx7J9LDaelBY78LIwABqAJkR3inFo7bLFFAokfOXYzztILu0equNOcijKe/O4ZR82GOf68Wn+LaWtfLHLyLtwpng7+Kn07go3xbVdcJHgsmjd7sPjaU4zpIiv3VRIt0FyDIfOnNJXAX2h6jdGMQQYIUZbX2beK2JBalepY0y65yPTJqX+9kt6nrZcyE0NYhVOLOXphUHd2TY411ctxh5Il2V3d5stDRDsBB68BsVxIJcIqg8RS5Kb2Npriw3HJ9U2zjJPgdG/7fX0hA9PmE7BaeNB93s25GNZiRdY05OxXNb9fZRTEk2/i121v3YvvqNKVMBfb51i8iUZGp/sSPVZX6RXBYxcJ12uIKJGLBMbstvIQLSi9UfoY9Kh2CDYzOvaqThPnidfWslbrV1J4uAeLT7eHV3kW1W5fVLZ7/kXgiJClQgZSnNiNheTCwJk3ZCuqeDCLZ8DQwdsS5nhkYdq6vlNzHbG7qEJgmre7F6+nN4bvk7yImsidR4X9LipxVsLYFi/VTjZ153ZHLtP/g4P72OJYvOSYN8g==
    postgres-password: AgACKXyLLXgAhF0GPWdm5nSXHelUni2NpowegMTodnYmUjy2+uz2EzgNEcXwPOfQ4/GRfKOFqTIZq28tIo2CmBhLDQ7VEcM4GoiPkZTZNB5vo0pxuUbwQHUwOz6rHLLITnd18LKXw57nlTk6jaBBOeSeq7dUXKL8IMd6a2qsYBR1jYJGXhhiTNhgu/HcT3OU5b/Xu5Yg3P+0tHePg3DRfqdA4H8w2W5QmYrWfG3iHlSOApuhyJCfB6xal/uqkUlHgzMwZBx3mfOr/DSsQe93fFyNbg28OYPl+xfP0/ExcTn7r3/J0FHn5zIcWDF5F/qKNNxYlRQnwV5j39vyg/t8RdssOY1BcFXhQlr8FBu36Vwzuz0+v7/0m2UP3eoocwlj657w8DqDCw6sf+kAXP+qQgKXLrzF6SeZ3OHsPoGtcXmlYztKKdcUUTdMljjFYIjd/I/0iBbx9pLxd9UYXbPiqLTvs3AmTa6BN3ZiWJ0STLE0HkfnBce+7K24cgs90bdmMi3j5yir8jVa7SgpyRY+nZRAejZWmdxEZO9QCXFkYmg34EJmUOkcUag3Gc8IMz0mz7IxrQK6OgeWn9u0yiO68oJ7gUGK3wQ2yQWS3z/PoejG/ykmCSopoUIinzSEf6UmVp19P3zQLglpjswwcAVe5OWsfbWHL+usv22okE0PrV0bucgk+ScZ/mm/mSDFannFpMG3KUcz7wtbrpKu9vg4CopNrkTyS+FTWfdQzE3Lvd/IiQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-auth
      namespace: postgresql
