---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database
  namespace: keycloak
spec:
  encryptedData:
    password: AgBO5BjfqmEU9gs6h6jPAhPKeGZTZkfPO4spfPNZgB2C4peVQNHBOoDC7VZOyqEY/Lcr+Kx7K0QpuGzMiFg/5DPOFbLFSyiFsggn6865fUg49GE3qrRoxRSq0+mKiF0F1QxAGCH9L85xCrrLUzeYe0BpM31SjOrp7yJoPuv2kFGxnG/1fTbNU/ahllhTuCyhfKbCbHfUgSVkntXzNhAflYUXs9hAyKR4dim7Iuh30fq2/RyOc0EZaTfRM0ckh5zjZrLeBRL9clWIPJDS+Ij0ONUrKrDnYuyhh2roTwzorxCIw1odjqOUP+TMrzRKflUtcVIVCOuJOK00cuyab5fIuMQ/tbSOOBQwuFpcG7oEZPmz9zPhj751HVABUp3l6IyJ4M2PHeIDftx19ihYaedVZmMbjVenlXtyLffUMT9HKkD9/uQWSop8gYhStHIQuPcJVw8rnhNQ8gD+x8zJ/8KSYtykJY1MpLegLjXuE+Q/6U+McBUGOX2McupGyaFBqDSzncVxHA3G2FtuOihz1BEy2jR0xlgWIHjzjV+qxhGcX0aPtve/o1DXRPvvLqbvedx+jCJFMHJrtWL58XANLM7GsV8asGMIOA6MchQm5FTYZXw+VqPHCIJa1xe5PTcwfwPPkOuZNw6hoG59MyBt/b9/TEiLCig+/9WJfhREZTGxAecmGV/HkrLUvG1asTbSkLIaUUdfPCrQztvodbOOYg9wqkcZ7vN/SUX35S0HmP3s1fkaTw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database
      namespace: keycloak
