---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCVDbbwSiQ9HcQivN0hjxJF1B5Of0V/rCoY4USOw1napbJKQFB460ZIz92avXhMHh7iFgHD3YziZNSJCmCV2gguaMd3/k6k3dftSF11CPb6OOm24iM3TphnMonJD7SNNH64IMDaWfbfbHwWTA1yclFDntyzaRrmKgZFYeOg7rqTD6sMMlrzXOkjgEx7COafeHtDp1b5tSZ1l4rkqjWX2kvuaYAq0jg7cQl2+jO4kkuMlbPVIGuejbhB53GqAU4tRiUMgZweI0Po99GZkjrfCWqJa67UTctkivt1tUY8o4VH5EYz82ToYEBP9GXfx322RbEjFSgHrpO6kQusUl0jzn1DXsZdCTPYtOu4+vSq9oz2jCf7ThYJeCJloF1+ssxm8EhxrpIyNDcUxVUGWkh1y+hwfU14hOrnBS+jeEzQXTOas+bIc/CnWHD16hZ0Fo5592q9DH/RU22HnwqAev83xKHigjl3P2Ptn/tspIn5bTcfKAHBTEOhTIHMgnXTUp0TXvknXaLIouuwQ80Wm3yrZg2pQM1BQBo3H1RFefzZnsUMicbn+/UQ9M1+aAuhM5xjNIoE31L4f8btMOCfoZQxH5gH9LcjCwb8pLo1mFTPFS1SUYnxenmGW1QoRSsjbjU81ZF11nS+v45JpRfXsAEK445Xz9TpalYwJf9pKtF+m3Qs+E4hhzYZ+y0RZ1ll7V2Qw76f/bgaf7qLyPlvRy7kyPhPdn4IbaVadS79A+/8
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
