---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-database
  namespace: keycloak
spec:
  encryptedData:
    password: AgA1Is8wEYYhnsg1u/OxT2AS7+cYgADYoxHcg5VkzywVZE9BqTSFIST8TDE6OrrycjNokgqqrs1WPyOM0bxr+mc7+thj8BB7wr8Jp6GSlS9thZG82eDPaYSNsdtWrTlqD+7yf2liKz+ZHozDa4RzhbW8V/JGt1ue1iLYPU7WV5FZNqyw+ofKkR9/Fy1R+094eqhb3t+/Oq/vldWKuzjzQvT06JE1w/vvj/iym4lCJwk93QoGpcT4EeDaqqVDWudt0ADq4TJzBDvNQm4gNBG+KaFwyPTin2Z8I3WhRCsvKXchkIYg/l3+GTXT1MMGC0SCOvzalbsiFuZcXOEB2pbKAmUIehbyO3C6O64IrFj99Ww26nBejHtJDAxwzvQ8mT2gtxiVh1zG5JKOd1S99gEpvJlR2S92hYogoqOy4Py+9ptf7J8omtFmicrVas8AJElp0w2CjGPvHpqgM3+Nt6mZTYL4xp+XHvz5GHrNN9QgMAXX52w+hXi0d9SGv99r5ZZ7BZ9+POIh/g/b/5pTmcwGiPhqtgdL302vLbueOuxyqBk9rnl43ALg1vC96jFfi9R+Ekzu0FM6THK8ZTfSRsVZ5RwGGS7jdv2pDQsFWxufs5FF0s4KVwR4WIeDlN/N6ELI9NKwCtpKpHYQjEdkInmH7XHsqUbdFkcNfp6B7essoGIXMQioFZaN6izswItbc53P5SBC/BJkn67j8/fsfMBd0iy4+MxqxTYOtVwTWoGa1vs5lQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-database
      namespace: keycloak
