apiVersion: v2
name: longhorn-wrapper
description: Wrapper Chart for Longhorn storage
type: application
version: 0.1.0

dependencies:
  - name: longhorn
    version: 1.11.2
    repository: https://charts.longhorn.io

