longhorn:
  persistence:
    defaultClass: false
    defaultClassReplicaCount: 2
    reclaimPolicy: Retain

  defaultSettings:
    defaultDataPath: /var/lib/longhorn
    defaultReplicaCount: 2
    storageMinimalAvailablePercentage: 25
    storageOverProvisioningPercentage: 100
    replicaSoftAntiAffinity: false
    replicaAutoBalance: best-effort
    orphanAutoDeletion: false
