apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: local-keycloak-platform
  namespace: fleet-local
spec:
  repo: https://github.com/ThomasTannenberg/local-kubernetes-keycloak-platform.git
  branch: main
  paths:
    - platform/cert-manager
    - platform/cert-manager-issuer
    - platform/longhorn
    - platform/postgresql
    - platform/traefik
    - platform/keycloak