postgresql:
  architecture: standalone

  image:
    registry: registry-1.docker.io
    repository: bitnami/postgresql
    tag: latest

  auth:
    username: keycloak
    database: keycloak
    existingSecret: keycloak-postgresql-auth
    secretKeys:
      userPasswordKey: password
      adminPasswordKey: postgres-password

  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 10Gi

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi