---
# Diese Datei ist eine Vorlage.
# Beim ersten Lauf von bootstrap-fleet.yml wird daraus automatisch secrets.yml erstellt.
# Danach müssen echte Passwörter in secrets.yml eingetragen werden.

keycloak_db_password: "keycloak-db-password"
postgres_admin_password: "postgres-admin-password"
keycloak_admin_password: "keycloak-admin-password"